### ISSUE TITLE
PING实现

### ISSUE THREAD

**Issue by KevinZonda** [KumaTea/mirror-tester#2]
可以考虑使用TCPing取代ICMP PING
使用TCP也更能展示实际数据（ICMP可以通过路由修改路由方式以和TCP不同）

**Comment by KumaTea** [comment]
谢谢提议！若有下一版更新就会实现这个功能。

**Comment by KumaTea** [comment]
有了有了 [ec97573](https://github.com/KumaTea/mirror-tester/commit/ec97573d35226387533076e7707ecd6235d5e7b4#diff-a3ce10d78630a2c81b2b06556316fcdec2bb91a24188a3a400fe147b25de1e21R6)
